first festure file
nabim777/mentorship2023 pull request #3
Opened 2023-12-05 09:49 UTC by SoniGautam

here feature file for login is added

2023-12-12 11:40 UTC, nabim777 commented on soni/tests/acceptance/stepDefinitions/loginContext.js
> +
```suggestion
```

2023-12-12 11:40 UTC, nabim777 commented on soni/tests/acceptance/stepDefinitions/loginContext.js
> +
```suggestion

```

2023-12-12 11:41 UTC, nabim777 commented on soni/tests/acceptance/stepDefinitions/loginContext.js
> +
```suggestion

```

2023-12-12 12:54 UTC, SagarGi requested changes
Please address the changes same as in this PR https://github.com/nabim777/mentorship2023/pull/1 since both seems similar to me.

2023-12-19 08:08 UTC, Grisha596 commented on soni/tests/acceptance/PageObjects/LoginPage.js
> +}
```suggestion
     }
     
}
```

2023-12-19 08:08 UTC, Grisha596 commented on soni/tests/acceptance/PageObjects/LoginPage.js
> +
```suggestion
```

2023-12-19 08:09 UTC, Grisha596 commented on soni/tests/acceptance/stepDefinitions/homePageContext.js
> +const HomePage = require("../PageObjects/HomePage.js")
```suggestion
const util = require('util');

const HomePage = require("../PageObjects/HomePage.js")
```

2023-12-19 08:10 UTC, Grisha596 commented on soni/tests/acceptance/stepDefinitions/homePageContext.js
> +  );
```suggestion
  });
```

2023-12-19 08:10 UTC, Grisha596 commented on soni/tests/acceptance/stepDefinitions/homePageContext.js
> +
```suggestion
```

2023-12-19 08:13 UTC, Grisha596 commented on soni/tests/acceptance/stepDefinitions/loginContext.js
> +const LoginPage = require("../PageObjects/LoginPage.js")
```suggestion

const LoginPage = require("../PageObjects/LoginPage.js")
```

2023-12-19 08:13 UTC, Grisha596 commented on soni/tests/acceptance/stepDefinitions/loginContext.js
> +
```suggestion



```

2023-12-19 08:14 UTC, Grisha596 commented on soni/tests/cucumber.conf.js
> +
```suggestion
```

2023-12-19 08:27 UTC, Grisha596 commented on soni/tests/acceptance/PageObjects/HomePage.js
> +
```suggestion
```

2023-12-19 08:43 UTC, Grisha596 commented on soni/tests/acceptance/stepDefinitions/homePageContext.js
> +const HomePage = require("../PageObjects/HomePage.js")
I think the name of the file would be better if it is createFileContext.js instead of homePageContext.js.

2023-12-20 17:06 UTC, Yogesh070 commented on soni/tests/acceptance/stepDefinitions/createFileContext.js
> +    expect(await page.locator(filelist)).toBeVisible()
maybe better variable name for filelist such as fileSelector

2023-12-20 17:07 UTC, Yogesh070 approved these changes

2023-12-26 03:31 UTC, nabim777 commented on soni/tests/acceptance/stepDefinitions/createFileContext.js
> +
```suggestion
```

2023-12-26 03:33 UTC, nabim777 commented on soni/tests/acceptance/stepDefinitions/createUserContext.js
> +
```suggestion
```

2023-12-26 03:33 UTC, nabim777 commented on soni/tests/acceptance/stepDefinitions/loginContext.js
> +  await loginPage.logintoHomePage(username, password)
If `expect` is there in `Given` step definition that will be good

2023-12-26 04:00 UTC, nabim777 commented on .github/workflows/ci.yml
> +on: #event
```suggestion
on:
```

2023-12-26 04:01 UTC, nabim777 commented on soni/tests/acceptance/PageObjects/HomePage.js
> +        // this.fileSelector = "//div[@aria-label='demo.txt']"
if not needed remove this
```suggestion
        // this.fileSelector = "//div[@aria-label='demo.txt']"
```

2023-12-26 06:35 UTC, nabim777 commented on soni/tests/acceptance/feature/createFile.feature
> +  And user has logged in with username "admin" and password "admin"
```suggestion
  Given user has logged in with username "admin" and password "admin"
```

2023-12-28 14:58 UTC, nabim777 commented on cucumber.conf.js
> +    slowMo:1000
```suggestion
    headless: true,
```

2024-01-03 12:15 UTC, Grisha596 approved these changes

2024-01-03 14:42 UTC, Yogesh070 reviewed
Formatting javascript files would be great as well.

2024-01-03 14:42 UTC, Yogesh070 commented on soni/tests/acceptance/stepDefinitions/createFileContext.js
> +  const expectedFile = fileName;
No need to ressign filename into new variable.

2024-02-03 11:27 UTC, merged